[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tick-off"
version = "1.1.0"
requires-python = ">=3.10.5"
authors = [{ name = "he-dev" }]
dependencies = []

